name: "🚀 publish"

on:
    push:
        branches:
          - main
     
permissions:
    id-token: write  # Required for OIDC
    contents: read

jobs:
    release:
        name: 🚀 publish
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v6
            - name: 🟢 node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public